# TpaPlis - Coded by T0m1keu
# For each setting, there is a small description.
# Please read each description carefully before changing anything.
# For more information visit: https://www.spigotmc.org/resources/tpaplus.111724/




